[configuration-files.containerd-config-toml]
# No override to path
template-path = "/usr/share/templates/containerd-config-toml_aws-dev"

# Docker
[services.docker]
restart-commands = ["/bin/systemctl try-restart docker.service"]
configuration-files = []

[settings.host-containers.control]
source = "gcr.io/google_containers/pause:3.2"

[settings.host-containers.admin]
enabled = true
source = "docker.io/koba789/bottlerocket-admin-container-amd64:v0.5.2-9b2ff1f5"

[settings.ntp]
time-servers = ["ntp.nict.jp"]
