[package]
name = "libcap"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-2.46.tar.gz"
sha512 = "d7d6d8d02701c2bef8f5095a0c923c1bb7033167894d573ad1c935d36d338adb9e58fe2e2779d5e9e8efaf5fe9bc87f43a85eafc733b76f953636038868d73d2"

[build-dependencies]
glibc = { path = "../glibc" }
libattr = { path = "../libattr" }
