[package]
name = "storewolf"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
bottlerocket-release = { path = "../../bottlerocket-release" }
datastore = { path = "../datastore" }
log = "0.4"
models = { path = "../../models" }
rand = { version = "0.8", default-features = false, features = ["std", "std_rng"] }
semver = "0.11"
simplelog = "0.9"
snafu = "0.6"
toml = "0.5"

[build-dependencies]
cargo-readme = "3.1"

[[bin]]
name = "storewolf"
path = "src/main.rs"

[lib]
name = "storewolf"
path = "src/lib.rs"
