[package]
name = "docker-engine"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/moby/moby/archive/v19.03.14/moby-19.03.14.tar.gz"
sha512 = "9ba589a2199ee272af50b60168a117a707c1fe0bfb039c8e4c0a9df68055add13b68b28e0937fdfeb9c42ec0e2936ac9ca3a671ff946d2d3f3e9d1bfe00ed6d1"

[build-dependencies]
glibc = { path = "../glibc" }
libseccomp = { path = "../libseccomp" }
systemd = { path = "../systemd" }
